// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBl2cU9nBjiV5iSHT30vHjiJsH98p8TycQ',
    appId: '1:638348977594:android:59d379350f7677ad926983',
    messagingSenderId: '638348977594',
    projectId: 'zad-frms-642c3',
    storageBucket: 'zad-frms-642c3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCur6thsak_V__7xyqiS171Skr0MkoDWSs',
    appId: '1:638348977594:ios:aa4f6c15b70f20d2926983',
    messagingSenderId: '638348977594',
    projectId: 'zad-frms-642c3',
    storageBucket: 'zad-frms-642c3.firebasestorage.app',
    iosBundleId: 'com.example.zadProject',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBRFehAZckmLlnbpfDf2e7pbu5nPzI7oWk',
    appId: '1:638348977594:web:837b289aae6963fb926983',
    messagingSenderId: '638348977594',
    projectId: 'zad-frms-642c3',
    authDomain: 'zad-frms-642c3.firebaseapp.com',
    storageBucket: 'zad-frms-642c3.firebasestorage.app',
  );

}